baseURL = "https://www.ty07.net"
title = "Not Good Father"
author = "YAMASHITA Takao"
copyright = "&copy; 2009-2020. All rights reserved."
DefaultContentLanguage = "ja"
languageCode = "ja-jp"
pagenate = "10"
theme = "anatole-ext"
enableEmoji = true
enableInlineShortcodes = true
enableGitInfo = true
hasCJKLanguage = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/page/about/"
    weight = 4

[Params]
subtitle = "The sound, old pond and frog jump into water."
logo = "/images/logo.jpg"
favicon = "/images/logo.jpg"

[Author]
author = "ac1965"
github = "ac1965"
twitter = "ac1965"
instagram = "ac1965"
